"""4.1 relationship

Revision ID: 1e70a3f32f6a
Revises: 219e7c2f933c
Create Date: 2024-05-08 18:46:01.368025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e70a3f32f6a'
down_revision: Union[str, None] = '219e7c2f933c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistics', 'indicators',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Показатели')
    op.alter_column('statistics', 'control_period',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Период контроля (отчетный)')
    op.alter_column('statistics', 'value_of_indicators',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Значения показателей')
    op.alter_column('statistics', 'max_amount_of_additional_bonus',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Максимальный размер доп премии (в % от оклада)')
    op.alter_column('statistics', 'note',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Примечание')
    op.alter_column('statistics', 'proposed_amount_of_additional_bonus',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Предпалагаемый размер дополнительной премии')
    op.alter_column('statistics', 'user_id',
               existing_type=sa.BIGINT(),
               comment='Ссылка на юзера кто создал запись',
               existing_comment='Ссылка на юзера',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistics', 'user_id',
               existing_type=sa.BIGINT(),
               comment='Ссылка на юзера',
               existing_comment='Ссылка на юзера кто создал запись',
               existing_nullable=False)
    op.alter_column('statistics', 'proposed_amount_of_additional_bonus',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Предпалагаемый размер дополнительной премии')
    op.alter_column('statistics', 'note',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Примечание')
    op.alter_column('statistics', 'max_amount_of_additional_bonus',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Максимальный размер доп премии (в % от оклада)')
    op.alter_column('statistics', 'value_of_indicators',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Значения показателей')
    op.alter_column('statistics', 'control_period',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Период контроля (отчетный)')
    op.alter_column('statistics', 'indicators',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Показатели')
    # ### end Alembic commands ###
