"""1 users

Revision ID: 4b254fd363c9
Revises: 
Create Date: 2024-05-04 19:56:56.672324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b254fd363c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='Уникальный идентификатор дела'),
    sa.Column('alias', sa.Uuid(), nullable=False, comment='Универсальный уникальный идентификатор'),
    sa.Column('login', sa.String(length=30), nullable=False, comment='Логин'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='Пароль'),
    sa.Column('surname', sa.String(length=60), nullable=False, comment='Фамилия'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Имя'),
    sa.Column('patronymic', sa.String(length=100), nullable=True, comment='Отчество'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Статус активности'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания'),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True, comment='Дата Деактивации'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('login'),
    comment='Пользователи'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
