"""5

Revision ID: b073b636c7f3
Revises: 5e42a2775c7d
Create Date: 2024-05-14 22:04:06.321523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b073b636c7f3'
down_revision: Union[str, None] = '5e42a2775c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'proposed_amount_of_additional_bonus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('proposed_amount_of_additional_bonus', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Предпалагаемый размер дополнительной премии'))
    # ### end Alembic commands ###
