"""5.1

Revision ID: c232b5e3387a
Revises: b073b636c7f3
Create Date: 2024-05-14 22:04:30.536156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c232b5e3387a'
down_revision: Union[str, None] = 'b073b636c7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('proposed_amount_of_additional_bonus', sa.Integer(), nullable=True, comment='Предпалагаемый размер дополнительной премии'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'proposed_amount_of_additional_bonus')
    # ### end Alembic commands ###
