"""3 statistics

Revision ID: ef56cd7f9787
Revises: 659352108911
Create Date: 2024-05-07 23:42:00.891690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef56cd7f9787'
down_revision: Union[str, None] = '659352108911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='Уникальный идентификатор дела'),
    sa.Column('alias', sa.Uuid(), nullable=False, comment='Универсальный уникальный идентификатор'),
    sa.Column('indicators', sa.String(), nullable=False, comment='Показатели'),
    sa.Column('control_period', sa.String(), nullable=False, comment='Период контроля (отчетный)'),
    sa.Column('value_of_indicators', sa.String(), nullable=False, comment='Значения показателей'),
    sa.Column('max_amount_of_additional_bonus', sa.String(), nullable=False, comment='Максимальный размер доп премии (в % от оклада)'),
    sa.Column('note', sa.String(), nullable=False, comment='Примечание'),
    sa.Column('proposed_amount_of_additional_bonus', sa.String(), nullable=False, comment='Предпалагаемый размер дополнительной премии'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Статус активности'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True, comment='Дата Деактивации'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    comment='Данные для расчета статистики о КПД'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###
